### PR TITLE
Compilations on Mac OSX

### PR DESCRIPTION
**Pull request by EiffL**
This PR adds Travis support for an OSX environment

### CODE REVIEW

**Comment by giordano** [comment]
There was #13 already :slightly_smiling_face:

**Comment by EiffL** [comment]
image
I forgot about it >.< ...... Let me take a look ^^'

**Comment by EiffL** [comment]
Yep..... it's pretty much the exact same thing :'-|

**Comment by EiffL** [comment]
Hummmm ok, so I'm not sure how to proceed with 2 PR doing the same thing..... just by virtue of this one getting a green light on Travis, I want to go ahead and merge it. Then I'll check for differences in #13 , I see that you also have support for llvm. 
But yeah gcc is intractable, I gave up as well

**Pull request merged**
