### PR TITLE
Initialise lensKernelTrue to 1 when zlens less than zero

### PR DESCRIPTION
**Pull request by austinpeel**
Step size tau was often nan when zlens was set to -1 in the config file. This was because lensKernelTrue wasn't initialised in this case (when nlp == 1 and zlens <= 0) the way lensKernel was. Adding this line fixes the problem.

### CODE REVIEW

**Comment by EiffL** [comment]
Hummmmm @austinpeel I must be blind I can't see which line you modified, can you point it to me?

**Comment by giordano** [comment]
Hiding whitespace changes help: https://github.com/CosmoStat/Glimpse/pull/15/files?diff=split&w=1

**Comment by EiffL** [comment]
I was looking for that option in the wrong place >.< Many thanks @giordano

**Review by EiffL — APPROVED** [review]
Ok, yes, that's a bug ^^' 
Thanks! @austinpeel

**Pull request merged**
